### PR TITLE
Fix ajax operation

### LINKED ISSUE #197: Boolean saveCallbacks in DcaAjaxOperationsListener with strict database
This issue relates to #196 but I guess we need another solution.

I tried to support haste v5 in m-vo/facebook-import, which uses the haste_ajax_operation for toggling - e.g. see: https://github.com/m-vo/contao-facebook-import/blob/main/src/Resources/contao/dca/tl_mvo_facebook.php#L69

But there is also a `save_callback` (https://github.com/m-vo/contao-facebook-import/blob/main/src/Resources/contao/dca/tl_mvo_facebook.php#L181) which returns a `boolean` value

The `boolean` value cannot be set in the database here:
https://github.com/codefog/contao-haste/blob/e32f31cfc4efc0653fa765963ffffedd3cb483c6/src/EventListener/DcaAjaxOperationsListener.php#L75-L78

You will get a database error 
```sql
Incorrect integer value: '' for column
```

How can we solve this problem? Can we cast the value after executing the `save_callback` or do we need to refactor the `save_callback` of the extension?

EDIT: This problem already exists in v4 😭 

see also: https://github.com/m-vo/contao-facebook-import/issues/36

### PR DESCRIPTION
**Pull request by rabauss**
This is a follow up of #200 and fixes #197

- Set the correct empty value on execute post actions
- Set the correct parameter types
- Cast the database value to string for equal comparison.
- Update example for toggle published

### CODE REVIEW

File: src/EventListener/DcaAjaxOperationsListener.php [hunk 1]
```diff
@@ -202,7 +211,7 @@ private function getDefaultButtonCallback(string $name, string $table, array $se
                 return '';
             }
 
-            $value = $row[$settings['field']];
+            $value = (string) $row[$settings['field']];
```
Comment (rabauss) [inline src/EventListener/DcaAjaxOperationsListener.php:214]: There might even be a better way than casting the database values to string to compare against the option value. But for my case it was working like that. what do you think?

**Review by Toflar — APPROVED** [review]
Imho we should merge that as is, yes.

**Comment by qzminski** [comment]
Released as 5.1.7, thank you @rabauss !
